name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    ci-workflow:
        name: CI
        uses: ./.github/workflows/ci-infra.yaml
        secrets: inherit

    cd-workflow:
        name: CD
        needs: ci-workflow
        uses: ./.github/workflows/cd-infra.yaml
        secrets: inherit